# Generated by Django 6.0.4 on 2026-05-22 09:42

import django.db.models.deletion
import pos_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_alter_category_created_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=pos_app.models.increment_order_menu_code, editable=False, max_length=20)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('ready_for_served', 'ready_for_served'), ('prepared', 'prepared')], default='pending', max_length=20)),
                ('total_order', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tax_order', models.FloatField(blank=True, default=0, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('table_resto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_resto_order_menu', to='pos_app.tableresto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order', to=settings.AUTH_USER_MODEL)),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_order', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
