# Generated by Django 6.0.4 on 2026-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0008_alter_order_order_status_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_payment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='subtotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
