# Generated by Django 6.0.4 on 2026-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0009_alter_order_total_order_alter_order_total_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuresto',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
