# Generated by Django 6.0.4 on 2026-05-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0010_alter_menuresto_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_resto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_resto_order', to='pos_app.tableresto'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_order_detail', to='pos_app.statusmodel'),
        ),
    ]
